// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using together_aspcore.Shared;

namespace together_aspcore.Migrations
{
    [DbContext(typeof(TogetherDbContext))]
    [Migration("20190720194917_add expirationdate and type fields for member")]
    partial class addexpirationdateandtypefieldsformember
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("together_aspcore.App.Member.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<bool>("Archived");

                    b.Property<DateTime?>("BirthDate");

                    b.Property<bool>("Disabled");

                    b.Property<string>("Email");

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<string>("FaceImage");

                    b.Property<string>("Name");

                    b.Property<string>("PassportImage");

                    b.Property<string>("Phone");

                    b.Property<string>("Phone2");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("together_aspcore.App.Member.MemberCredentials", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.HasKey("MemberId");

                    b.ToTable("MembersCredentials");
                });

            modelBuilder.Entity("together_aspcore.App.Member.MemberFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayFileName");

                    b.Property<string>("FileName");

                    b.Property<int>("MemberId");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
